[package]
name = "pods"
version = "2.0.3"
authors = ["Marcus Behrendt <marcus.behrendt.86@gmail.com>"]
edition = "2021"

[dependencies]
adw = { version = "0.6", package = "libadwaita", features = ["v1_4"] }
anyhow = "1"
ashpd = { version = "0.8", default-features = false, features = ["gtk4", "tokio"] }
futures = { version = "0.3", default-features = false }
gettext-rs = { version = "=0.7.0", features = ["gettext-system"] }
gtk = { version = "0.8", package = "gtk4", features = ["gnome_45"] }
indexmap = { version = "2", features = ["serde"] }
log = "0.4"
names = { version = "0.14", default-features = false }
oo7 = { version = "0.2", default-features = false, features = ["native_crypto", "tokio"] }
panel = { version = "0.4", package = "libpanel", features = ["adw_v1_2"] }
paste = "1"
podman-api = { git = "https://github.com/vv9k/podman-api-rs.git", commit = "363d945b9b9905c50dfa0bfe0f9331f9fdeef079", default-features = false }
serde = "1"
serde_json = "1"
sourceview5 = { version = "0.8", features = ["gtk_v4_12"] }
syslog = "7"
tokio = "1"
tokio-tar = { version = "0.3", default-features = false }
vte = { version = "0.13", default-features = false }
vte4 = "0.7"

[profile.release]
lto = true
codegen-units = 1
