[package]
name = "pods"
version = "1.1.1"
authors = ["Marcus Behrendt <marcus.behrendt.86@gmail.com>"]
edition = "2021"

[dependencies]
adw = { version = "0.3", package = "libadwaita", features = ["v1_3"] }
anyhow = "1"
ashpd = { version = "0.4", default-features = false, features = ["gtk4", "tokio"] }
futures = { version = "0.3", default-features = false }
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk = { version = "0.6", package = "gtk4", features = ["gnome_44"] }
indexmap = { version = "1", features = ["serde"] }
log = "0.4"
names = { version = "0.14", default-features = false }
once_cell = "1"
panel = { version = "0.2", package = "libpanel" }
paste = "1"
podman-api = { version = "0.10", default-features = false }
serde = "1"
serde_json = "1"
sourceview5 = "0.6"
syslog = "6"
tokio = "1"
tokio-tar = "0.3"
vte = { version = "0.11", default-features = false }
vte4 = "0.6"

[profile.release]
lto = true
